apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-mysql-deployment
  labels:
    app: jenkins-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-mysql-pod
  template:
    metadata:
      labels:
        app: jenkins-mysql-pod
      annotations:
        pod-name: jenkins-mysql-pod
    spec:
      containers:
      - name: jenkins-mysql-pod
        image: mysql:8.4  # The MySQL version
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ""  # empty password as per docker-compose
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_USER
          value: "petclinic"
        - name: MYSQL_PASSWORD
          value: "petclinic"
        - name: MYSQL_DATABASE
          value: "petclinic"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        #- name: mysql-config-volume  # New volume for configuration
        #  mountPath: /etc/mysql/my.cnf  # MySQL configuration path
        #  subPath: my.cnf  # This ensures we only overwrite the specific file
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-jenkins
      - name: mysql-initdb
        emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-mysql-service
  labels:
    app: jenkins-mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31710
  selector:
    app: jenkins-mysql-pod
  type: NodePort