apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: jenkins
  name: jenkins-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: jenkins