apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-shared-pv
  namespace: jenkins
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/jenkins-shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-shared-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi